version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: betalent_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: betalent_payment
    volumes:
      - betalent_mysql_data:/var/lib/mysql

  gateways-mock:
    image: matheusprotzen/gateways-mock
    container_name: betalent_gateways
    ports:
      - "3001:3001"
      - "3002:3002"

volumes:
  betalent_mysql_data: